/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_dwmblocks.h"
#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_winicon.h"
#include "bar_tabgroups.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "autostart.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "fsignal.h"
#include "floatpos.h"
#include "focusurgent.h"
#include "inplacerotate.h"
#include "movestack.h"
#include "pertag.h"
#include "restartsig.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "sticky.h"
#include "tagswapmon.h"
#include "togglefullscreen.h"
#include "unfloatvisible.h"
#include "vanitygaps.h"
#include "warp.h"
#include "zoomswap.h"
#include "xrdb.h"
/* Layouts */
#include "layout_flextile-deluxe.h"

