/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status2d.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_winicon.c"
#include "bar_tabgroups.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "autostart.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "fsignal.c"
#include "floatpos.c"
#include "focusurgent.c"
#include "inplacerotate.c"
#include "movestack.c"
#include "pertag.c"
#include "restartsig.c"
#include "renamed_scratchpads.c"
#include "sticky.c"
#include "tagswapmon.c"
#include "togglefullscreen.c"
#include "unfloatvisible.c"
#include "vanitygaps.c"
#include "warp.c"
#include "zoomswap.c"
#include "xrdb.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_flextile-deluxe.c"

